### PR TITLE
[build] Port Why3 1.2.0

### PR DESCRIPTION
**Pull request by ejgallego**
Why3 code still not 100% good, need update from EasyCrypt.

### CODE REVIEW

**Comment by strub** [comment]
What updates do you need from EasyCrypt?

**Comment by ejgallego** [comment]
> What updates do you need from EasyCrypt?

Thanks @strub , I'd need Why 1.X support in the main branch; I guess I can use the `deploy-why3-1.0` branch. Is that branch going to be merged into 1.0 soon?

By the way, I ported the core of EC to Dune, let me know if you are interested in a PR.

**Comment by strub** [comment]
I am currently porting EasyCrypt to Why3 1.x. On the EasyCrypt side, this was not that hard... but were missing some features removed in Why3 0.8.x. The branch should be reading in a few weeks.

Regarding dune, I was planning to move to it at some point, but after the move to Why 1.x.

**Comment by ejgallego** [comment]
> I am currently porting EasyCrypt to Why3 1.x. On the EasyCrypt side, this was not that hard... but were missing some features removed in Why3 0.8.x. The branch should be reading in a few weeks.
> 
> Regarding dune, I was planning to move to it at some point, but after the move to Why 1.x.

Merci for the information Pierre-Yves; I'd like indeed to vendor some parts of EasyCrypt as they are pretty convenient; I will wait for the Why3 branch to be done and then I will submit my Dune branch in case it could be helpful to you.

**Pull request merged**
